export const initialUsers = [
  {
    id: "CSH-001",
    username: "janedoe12",
    firstName: "Jane",
    middleName: "Marie",
    lastName: "Doe",
    name: "Jane Doe",
    role: "Cashier",
    email: "jane.doe@riderscityhub.ph",
    phone: "0917-123-4567",
    address: "Manila, Philippines",
    status: "Active",
    dateCreated: "2026-08-20",
  },
  {
    id: "CSH-002",
    username: "johndoe24",
    firstName: "John",
    middleName: "Robert",
    lastName: "Doe",
    name: "John Doe",
    role: "Cashier",
    email: "john.doe@riderscityhub.ph",
    phone: "0918-234-5678",
    address: "Quezon City, Philippines",
    status: "Inactive",
    dateCreated: "2026-08-22",
  },
  {
    id: "CSH-003",
    username: "jamessmith123",
    firstName: "James",
    middleName: "A.",
    lastName: "Smith",
    name: "James Smith",
    role: "Cashier",
    email: "james.smith@riderscityhub.ph",
    phone: "0919-345-6789",
    address: "Pasig, Philippines",
    status: "Archived",
    dateCreated: "2026-08-24",
  },
  {
    id: "CSH-004",
    username: "abigailsantos",
    firstName: "Abigail",
    middleName: "L.",
    lastName: "Santos",
    name: "Abigail Santos",
    role: "Admin",
    email: "abigail@riderscityhub.ph",
    phone: "0920-456-7890",
    address: "Makati, Philippines",
    status: "Active",
    dateCreated: "2026-08-25",
  },
];

export const initialLoginActivities = [
  {
    id: "LOG-001",
    userId: "CSH-001",
    username: "janedoe12",
    name: "Jane Doe",
    role: "Cashier",
    loginTime: "Aug 26, 10:35 AM",
    loginTimeout: "Aug 26, 7:45 PM",
    status: "Active",
  },
  {
    id: "LOG-002",
    userId: "CSH-002",
    username: "johndoe24",
    name: "John Doe",
    role: "Cashier",
    loginTime: "Aug 27, 09:35 AM",
    loginTimeout: "Aug 27, 7:50 PM",
    status: "Inactive",
  },
  {
    id: "LOG-003",
    userId: "CSH-004",
    username: "abigailsantos",
    name: "Abigail Santos",
    role: "Admin",
    loginTime: "Aug 28, 08:15 AM",
    loginTimeout: "Aug 28, 6:00 PM",
    status: "Active",
  },
];

export const initialAuditLogs = [
  {
    id: "AUD-001",
    dateTime: "Aug 26, 10:35 AM",
    user: "Admin",
    action: "Added",
    details: "Added a new user",
  },
  {
    id: "AUD-002",
    dateTime: "Aug 27, 09:35 AM",
    user: "Cashier",
    action: "Completed a sale",
    details: "Transaction #001",
  },
  {
    id: "AUD-003",
    dateTime: "Aug 28, 02:20 PM",
    user: "Admin",
    action: "Updated",
    details: "Modified user permissions for CSH-002",
  },
];

export const initialArchives = [
  {
    id: "ARC-001",
    dateArchived: "Aug 26, 10:35 AM",
    archivedBy: "Abigail Santos",
    userId: "CSH-002",
    role: "Cashier",
    fullName: "James Smith",
    username: "jamessmith123",
  },
  {
    id: "ARC-002",
    dateArchived: "Aug 27, 10:35 AM",
    archivedBy: "Abigail Santos",
    userId: "CSH-003",
    role: "Cashier",
    fullName: "Jane Doe",
    username: "janedoe12",
  },
];
